[Flags]
  configurational = true        # use configurational force

[DynCrack]
  criterion = "MERR"
  crit_val = 4.5e-4
  velocity = 2.0                # here only for plotting
  domain_size = [0.125, 0.125]

  # list of cracks to include in propagation
  [[DynCrack.Cracksets]]
  tag = 0                       # must match ID in Geometry.Cracks, determines BCs
  invert = false                # invert crack direction?

