[Flags]
  configurational = true

# any definitions for simulation of dynamic cracks
[DynCrack]
  criterion = "MERR"
  crit_val = 2.4e-5
  velocity = 1.0
  domain_size = [0.125, 0.125]
# domain_extend = [8, 8]
# d_min = 0.01

  # list of cracks to include in propagation
  [[DynCrack.Cracksets]]
  tag = 0                 # must match ID in Geometry.Cracks, determines BCs
  invert = false          # invert crack direction?
  direction = [1, 0, 0]

